### ISSUE TITLE
BUG some times the folder tests/.phpsu gets created. This should never happen

### ISSUE THREAD

**Issue by Kanti** [phpsu/phpsu#87] opened 2019-02-20 16:44 UTC

**Comment by Kanti** [comment] 2019-03-02 10:05
@ChrisB9 I did not see this on may system, can you confirm that this is no problem anymore?

**Comment by ChrisB9** [comment] 2019-03-02 11:49
i cannot reproduce it anymore - seems like this bug has vanished
closing this for now

**Closed by ChrisB9** 2019-03-02 11:49 UTC
Labels: bug
